### PR TITLE
Update @modulus/standard

### LINKED ISSUE #12: Update standard

### PR DESCRIPTION
**Pull request by theworkflow**
- Bump `@modulus/standard` from `v0.6.0` --> `v1.0.0`

Closes #12

### CODE REVIEW

**Comment by musgravejw** [comment]
👍

**Comment by franvarney** [comment]
:+1: but are you gonna relint?

**Comment by theworkflow** [comment]
Already did. Passed 😄

**Comment by jackboberg** [comment]
:shipit:

**Pull request merged**
